import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* <Script
          id="crawbat-chat-widget"
          src="https://widget.crawbat.com/chat-widget.js"
          strategy="afterInteractive"
          data-title="Support Chat"
          data-position="right"
          data-primary-color="#000000"
          data-welcome-message="Hello! I am your virtual assistant. How can I help you today?"
          data-client-id="beta"
          data-widget-key="pub_beta_test_456"
          data-show-badge="true"
          data-badge-text="AI powered"
          data-api-url="https://api.crawbat.com/chat"
          data-widget-config-url="https://api.crawbat.com/widget-config"
          data-use-mock-api="false"
          data-mock-error="false"
          data-fallback-message="Sorry, something went wrong. Please try again later."
          data-request-timeout="12000"
          data-contact-email="support@example.com"
          data-contact-phone="+1 555 010 100"
          data-contact-url="https://example.com/support"
        /> */}

        <Script
          id="crawbat-chat-widget"
          src="https://widget.crawbat.com/chat-widget.js"
          strategy="afterInteractive"
          data-title="Support Chat"
          data-position="center"
          data-primary-color="#000000"
          data-welcome-message="Hello! I am your virtual assistant. How can I help you today?"
          data-client-id="acme"
          data-widget-key="pub_acme_test_123"
          data-show-badge="true"
          data-api-url="https://api.crawbat.com/chat"
          data-widget-config-url="https://api.crawbat.com/widget-config"
          data-use-mock-api="false"
          data-mock-error="false"
          data-fallback-message="Sorry, something went wrong. Please try again later."
          data-request-timeout="12000"
          data-contact-email="support@example.com"
          data-contact-phone="+1 555 010 100"
          data-contact-url="https://example.com/support"
        />
      </body>
    </html>
  );
}